name: CI - Deploy Infra Kubernetes

on:
  push:
    branches:
      - main
      - homologation
      - 'feature/**'
  workflow_dispatch:

env:
  TERRAFORM_API_GW_DIR: infra/terraform
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || 'homologation' }}

jobs:
  deploy-gateway:
    name: Deploy Infra Kubernetes
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'homologation' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Terraform Gateway Init
        working-directory: ${{ env.TERRAFORM_API_GW_DIR }}
        run: terraform init -backend-config="key=kubernetes/${{ env.ENVIRONMENT }}/terraform.tfstate"

      - name: Terraform Gateway Apply
        working-directory: ${{ env.TERRAFORM_API_GW_DIR }}
        run: terraform apply -auto-approve -var="arn_user_homolog=${{ vars.ARN_USER_HOMOLOG }}" -var="arn_user_prod=${{ vars.ARN_USER_PROD }}" -var="arn_user_dev=${{ vars.ARN_USER_DEV }}"
        env:
          TF_VAR_environment: ${{ env.ENVIRONMENT }}