name: Terraform RDS Deploy

on:
  push:
    branches:
      - main
      - homologation
      - production

jobs:
  deploy-main:
    name: Deploy MAIN (manual approval)
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment:
      name: main
      # este environment terá aprovação manual no GitHub

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2

      - name: Deploy MAIN
        run: |
          cd envs/dev
          terraform init
          terraform apply -auto-approve

  deploy-homologation:
    name: Deploy HOMOLOGATION (automatic)
    if: github.ref == 'refs/heads/homologation'
    runs-on: ubuntu-latest

    environment:
      name: homologation

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2

      - name: Deploy HOMOLOGATION
        run: |
          cd envs/homologation
          terraform init
          terraform apply -auto-approve

  deploy-production:
    name: Deploy PRODUCTION (automatic)
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2

      - name: Deploy PRODUCTION
        run: |
          cd envs/production
          terraform init
          terraform apply -auto-approve
